watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --ahk"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start --ahk"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 6
      left: 6
      bottom: 2
      right: 6
    widgets:
      left: ["app_button", "komorebi_workspaces", "github", "media"]
      center: []
      right: ["traffic", "volume", "language", "weather", "memory", "cpu", "battery", "microphone", "bluetooth", "wifi", "clock","power_menu"]
widgets:
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u26a1 Offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: true
      animation: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

  #traffic:
    #type: "yasb.traffic.TrafficWidget"
    #options:
      #label: "<span>\udb82\udcfa</span> \uea9a{download_speed} \ueaa1{upload_speed}"
      #label_alt: "<span>\udb82\udcfa</span> Download {download_speed} | Upload {upload_speed}"
      #update_interval: 1000
      #callbacks:
        #on_left: "toggle_label"
        #on_right: "exec cmd /c Taskmgr"

  #apps:
    #type: "yasb.applications.ApplicationsWidget"
    #options:
      #label: "{data}"
      #app_list:
        #- { icon: "File", launch: "explorer" }
        #- { icon: "Code", launch: "code" }
        #- { icon: "Terminal", launch: "wt" }
        #- { icon: "Notepad", launch: "notepad" }
  app_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\uf40e</span>"
      label_alt: "<span>\uf40e</span>"
      class_name: "app-button"
      callbacks:
        on_left: "exec start_menu"

  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span>\uf11c</span>{lang[country_code]}"
      update_interval: 5
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\udb83\ude17</span>{%a %b %d %H:%M}"
      label_alt: "<span>\udb83\ude17</span>{%A, %d %B %Y %H:%M}"
      timezones: []
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span>\uf2c9 {temp_c} - \uef2a {max_temp_c} - \udb85\udd06 {humidity}"
      label_alt: "<span>{icon}</span> {temp_c}"
      api_key: 'dcc2817508f54b0a9b0165741242110'
      update_interval: 10800 #Update interval in seconds, Min 600
      hide_decimal: true
      location: 'Necochea, Buenos Aires'
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span>\uf011</span>"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200 # Milisecond 
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        signout: ["\udb80\udf43","Sign out"]
        hibernate: ["\uf28e","Hibernate"]
        sleep: ["\u23fe","Sleep"]
        cancel: ["","Cancel"]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation: true
      icon_size: 14
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      label_alt: "<span>\udb80\udf5c</span>"
      class_name: "win-btn"
      callbacks:
        on_left: "exec start_menu"
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\udb81\udca2</span> \uea9a{download_speed} \ueaa1{upload_speed}"
      label_alt: "<span>\udb81\udca2</span> Download {download_speed} | Upload {upload_speed}"
      update_interval: 1000
      callbacks:
        on_left: 'toggle_label'
        on_right: 'exec cmd /c Taskmgr'
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      update_interval: 1000
      charging_options:
        icon_format: "{charging_icon}"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "{volume_label} {space[used][gb]} / {space[total][gb]}"
        label_alt: "{volume_label} {space[used][percent]}"
        volume_label: "C"
        update_interval: 60
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec explorer C:\\" # Open disk C in file explorer
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: '{title} - {artist}'
      label_alt: "{title}"
      max_field_size:
        label: 38
        label_alt: 30
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16 # Set to 0 for square corners
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "\uefc5 {virtual_mem_used}/{virtual_mem_total}"
      label_alt: '\uf538 VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%'
      update_interval: 5000
      callbacks:
        on_left: 'toggle_label'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{device_name}"
      icons:
        bluetooth_on: "<span style='color: blue;'>\uf293</span>"
        bluetooth_off: "<span style='color: #665C54;'>\udb80\udcb2</span>"
        bluetooth_connected: "\udb80\udcb1"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span> {data}"
      label_alt: "Notifications {data}"
      token: env # GitHub Personal access tokens (classic) https://github.com/settings/tokens
      max_notification: 20 # Max number of notification displaying in menu max: 50
      only_unread: false # Show only unread or all notifications;
      max_field_size: 54 # Max characters in title before truncation.
      menu_width: 400
      menu_height: 400
      menu_offset: 240
      update_interval: 120 # Check for new notification in seconds
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: '<span>{icon}</span>'
      label_alt: '<span>{icon}</span> {level}%'
      icons:
        normal: "<span style='color: #EA6962;'>\uf130</span>"
        muted: "\uf131"
      callbacks:
        on_left: 'toggle_mute'
        on_middle: 'toggle_label'
        on_right: 'exec cmd.exe /c start ms-settings:sound'
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 3000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      wifi_icons: [
        "\udb82\udd2e",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-20% strength
        "\udb82\udd22",  # Icon for 21-40% strength
        "\udb82\udd25",  # Icon for 41-80% strength
        "\udb82\udd28"   # Icon for 81-100% strength
      ]
